### ISSUE TITLE
Data page d'accueil

### ISSUE THREAD

**Issue by millette** [alclro/mmmm#1]
Avoir tout le JSON nécessaire (dans data/ ou dans CouchDB) pour l'affichage complet de la page d'accueil (articles, layout, brèves, etc.)

**Comment by alainf** [comment]
Actuellement 5 articles
folder "/data/articles-a-j/" contient 10 articles
fichier "/data/list1.json" = sections de Accueil
fichier "/data/list2.json" = sujets de Accueil
Aujourd'hui je ferai une quinzaine de breves.
Avant de te fournir BEAUCOUP de data, j'attend prudemment.

**Comment by alainf** [comment]
Je viens de pusher 38 fichiers json: 4 breves, 24 articles, et les 10 termes qui qualifient ces articles. Il y a 2 sujets en primeur: "Économie" et "Agriculture". Naviguer vers ces 2 sujets affichera des contenus différents.

**Comment by millette** [comment]
db: machina (au lieu de ya)

**Comment by millette** [comment]
J'ai un unzippé les fichiers info/add-to-couch/articles-2016...zip puis j'ai runné ```yarn run jsonlint``` pour trouver un paquet de *dangling commas*.

> ✖ 146 problems (146 errors, 0 warnings)

Je vais voir le meilleur moyen de nettoyer ça.

**Comment by alainf** [comment]
Au-moins une partie de la non-conformité est dû au fait que j'ai passé au-peigne-fin les fichiers "test-" mais PAS les fichiers json en appui à ces tests. Cette fois-ci les jsons lieu, page, pers et terme n'ont pas été corrigés. Oops!

**Comment by millette** [comment]
J'ai un script qui corrige pas mal tout, sauf 2-3 touchups manuel et ce fichier qui est weird (voir framateam):
https://github.com/alclro/mmmm/blob/dev-robin/info/add-to-couch/bad/test-2016-12-01-18-00-24-random.json
