### ISSUE TITLE
Compléter la page "detail"

### ISSUE THREAD

**Issue by alainf** [alclro/mmmm#14]
- [x] field "description" peut contenir du HTML: utiliser "< % ="
- [x] field "contenu" peut contenir du HTML: utiliser "< % ="
- [x] if iscopyright est true, then branchement vers markup "externe", else markup "interne" (voir #28 )
- [x] markup "externe" affichera à gauche le même markup que dans l'accueil
- [x] ensuite markup "externe" affichera le bloc "consultation"
- [x] partout où on affiche un ID: afficher un hyperlien avec le terme en langue naturelle
- [x] plus spécifiquement: partout sauf field "couch-id et sauf "nom-machine".

**Comment by alainf** [comment]
En ce moment, avec livecode et mes jsons, je suis en train de préparer les données qui permettront à toutes les valeurs qui sont des IDs d'obtenir les informations supplémentaires; comme entre-autres le terme en langue naturelle, dans les 6 langues que nous utilisons. Ces données sont, bien-entendu, en format json et seront validées avec jsonlint. C'est, d'ailleurs, les mêmes données qui ouvriront la porte aux sections et aux sujets.

**Comment by millette** [comment]
On dirait qu'une partie du travail est déjà fait, non? Par exemple:
https://github.com/alclro/mmmm/blob/master/templates/detail.html#L24

Tu peux me pointer (dans detail.html ou ailleurs, quelles lignes) les changements devraient avoir lieu?

Dans le document que tu cites ici, les lignes 29 et 30.
29  <%= partials.detailedMemeQueLead(data) %>
30  <%= partials.detailedConsultation(data) %>

Le partial de la ligne 29 est juste un placeholder. Son contenu est bidon. Ce qu'il faut c'est le même markup que l'Article avait dans l'accueil, donc la même programmation que les apercus d'article de l'accueil. Il s'agit du même json, avec les mêmes fields, donc reproduisible.

Le partial de la ligne 30 n'apparaît pas, pour aucun des 7 articles avec isCopyright=true.

D'ailleurs, pourrais-tu svp retirer les lignes suivantes: 31, 34, 57, 60
car je ne souhaite plus cette condition: <% if (data.app.usertype) { %>

**Comment by millette** [comment]
Je vois mal ce que je peux faire, si c'est du côté template. C'est plus un issue pour toi, je me trompe? Si y'en a un bout pour moi, ça devrait être un issue supplémentaire. Quelque chose de "actionnable", de préférence :-)

**Comment by millette** [comment]
C'est encore un peu confu.

Est-ce que tu peux ouvrir des issues pour chacun des éléments qui restent à faire? Ça va aider à clarifier chaque point.

En fait, je crois que c'est tout règlé maintenant, mais j'aimerais que tu puisses confirmer.

Pour isCopyright, voici deux exemples (true et false):
http://localhost:8090/en/detail/lead-2016-12-03-18-00-42-random
http://localhost:8090/en/detail/lead-2016-12-03-18-00-06-random

Voir la source HTML (CTRL-u) pour savoir lequel est true et lequel est false.

Si tout est bon, tu peux fermer le issue stp? Merci @alainf
