### ISSUE TITLE
Fix breadcrumbs

### ISSUE THREAD

**Issue by millette** [alclro/mmmm#18]

**Comment by millette** [comment]
Pas de breadcrumb si une seule page

**Comment by millette** [comment]
Le breadcrumb représente en fait 2 choses: un mini-pager (page précédente et suivante) ainsi qu'une hierarchie.

Pour les sections et sujets, il faut remonter la hierarchie pour en afficher les liens. Par contre, les docs, contiennent un champ ```enfants```. Je pourrais accessoirement faire un view qui prend ce champ pour établir une hierarchie avec quelques queries.

Cependant, si on est pour utiliser un champ ```parent```, ça simplifierait la tâche.

Il existe aussi un champ breadcrumb textuel, mais il contient un autre encodage des noms des sections et sujets (traits d'unions au lieu des espaces, etc.).

Si le champ breadcrumb contenait un array de parents de parents de parents... ça serait 1000 fois mieux.

**Comment by alainf** [comment]
Fais ce que tu penses être la meilleure solution. Au besoin, je m'ajusterai.

**Comment by millette** [comment]
Plusieurs sections n'ont pas de parent selon la DB. Il reste ça à corriger. En cours.
