### ISSUE TITLE
Peaufiner markup du template detail quand isCopyright=true

### ISSUE THREAD

**Issue by alainf** [alclro/mmmm#28]
Quand isCopyright=true, il serait bien d'afficher, dans la colonne gauche, le même markup que l'article avait dans les pages accueil, section, sujet.

En-dessous de cette reprise du lead, svp afficher le bloc "Consultation". Je n'ai pas-encore vu ce bloc apparaître. Soit qu'il n'est jamais produit (programmation), ou c'est qu'il y a aucun article avec le field isCopyright = true (donc une question de données). Svp, s'il le faut, assigner true au field isCopyright d'un article quelconque.

**Comment by millette** [comment]
OK, c'est pas mal clair. Je verrai sur le terrain si j'ai des questions.

**Comment by millette** [comment]
Selon http://localhost:8090/en/demo/by/isCopyright on aurait des deux (copyright true et false).
