### ISSUE TITLE
Variable "page" pour chacun des templates

### ISSUE THREAD

**Issue by alainf** [alclro/mmmm#4]
Pour que je puisse remplacer les données hardcodées par des variables, et accomplir ceci pendant le temps que la bd ne le fera pas, tout en continuant d'afficher les pages actuelles avec leurs données de type placeholder, il faut une passe-passe Hapi qui auto-associe chacun de nos templates avec un fichier json correspondant. Genre "/data/accueil.json" pour le template "accueil". Lorsque le template se charge, il y aura donc une variable "page".

## Toutes les pages
- [ ] page.title (window)
- [ ] page.titre (affiché dans la page)
- [ ] page.soustitre

## Template accueil
- [ ] page.sections (items)
- [ ] page.sujets (items)

## Template section
- [ ] page.sections (items)
- [ ] page.section.terme
- [ ] page.section.id
- [ ] page.breadcrumb (items)

## Template sujet
- [ ] page.sujets (items)
- [ ] page.sujet.terme
- [ ] page.sujet.id
- [ ] page.breadcrumb (items)

Plus spécifiquement:
page					{OBJ}
page.id					"web-timestamp-random"
page.lastPage				2000
page.thisPage				1
page.signet				"title de la fenêtre"
page.titre					"titre de la page"
page.soustitre				"soustitre de la page"
page.section				{OBJ}
page.section.terme		"Entreprise"
page.section.id			"terme-timestamp-random"
page.sujet				{OBJ}
page.sujet.terme			"Agriculture"
page.sujet.id				"terme-timestamp-random"
page.breadcrumb			[ITEMS]
page.sections				[ITEMS]
page.sujets				[ITEMS]
page.articles				[ITEMS]
page.breves				[ITEMS]

**Comment by millette** [comment]
On s'arrange via CouchDB finalement.

**Comment by alainf** [comment]
Je suis d'accord que le data provienne de Couch, au lieu de provenir d'un fichier, mais le besoin d'avoir cette variable, pour TOUTES les pages, est encore un besoin. Car cette variable me permettrait de transformer les strings hard-coded, par des assignations et partials expriméEs en js. Pages statiques, dont les liens sont en haut de l'écran, ont beaucoup de strings que nous voudrons modifier à notre gré sans modifier la programmation. Autrement-dit "data-driven". Et me permettant aussi d'ajouter strings de manière ad-hoc, aka "custom" en fonction de chaque page.

**Comment by millette** [comment]
Comme on arrive à afficher le site maintenant, tel quel (hardcodé dans les templates), le mieux serait probablement de splitter ce *issue* en plusieurs, au cas par cas, ou alors d'éditer ce *issue* avec le markup pour faire une liste de checkbox comme #9 en identifiant les champs/valeurs qui sont déjà disponibles dans accueil.

**Comment by alainf** [comment]
## Toutes les pages
- [ ] page.title (window)
- [ ] page.titre (affiché dans la page)
- [ ] page.soustitre

## Template accueil
- [ ] page.sections (items)
- [ ] page.sujets (items)

## Template section
- [ ] page.sections (items)
- [ ] page.section.terme
- [ ] page.section.id
- [ ] page.breadcrumb (items)

## Template sujet
- [ ] page.sujets (items)
- [ ] page.sujet.terme
- [ ] page.sujet.id
- [ ] page.breadcrumb (items)

**Comment by alainf** [comment]
### page Entreprise du template section

page.section.terme = "Entreprise",

page.section.id = "terme-2015-12-06-16-23-30-86966220631",

page.breadcrumb = ["section:", "Accueil", "Entreprise", "<", "Page 1", ">"],

page.sections = [
  "Acteurs de l'entreprise",
  "Formes d'organisations",
  "Industries",
  "Investissement",
  "L'environnement externe de l'entreprise",
  "L'environnement interne de l'entreprise",
  "Secteurs industriels",
  "Statut juridique"
]

### page Agriculture du template sujet

page.sujet.terme = "Agriculture",

page.sujet.id = "terme-2015-12-06-16-24-22-86966223762",

page.breadcrumb = ["sujet:", "Accueil", "Agriculture", "<", "Page 1", ">"],

page.sujets = [
  "Acériculture",
  "Agriculture généralités",
  "Agrocarburants",
  "Aquaculture",
  "Botanique",
  "Conservation des ressources naturelles",
  "Expérimentation agricole",
  "Foresterie",
  "Industrie alimentaire",
  "Pêche",
  "Sciences de l'alimentation",
  "Viticulture",
  "Zootechnie (agriculture)"
]

### page Acériculture du template sujet

page.sujet.terme = "Acériculture",

page.sujet.id = "terme-2015-12-06-16-24-22-86966223771",

page.breadcrumb = ["sujet:", "Accueil", "Agriculture", "Acériculture", "<", "Page 1", ">"],

page.sujets = "Vous êtes à la fin de cette branche de la taxonomie de sujets."

**Comment by alainf** [comment]
La variable page.sections serait plutôt codée ainsi : 
NB: exemple donné ici est celui de la page accueil

"sections":
 [
	{
      terme: "Académique",
      id: "terme-2015-12-06-16-23-42-86966221325"
	},
   {
      terme: "Entreprise",
      id: "terme-2015-12-06-16-23-30-86966220631"
	},
	{
      terme: "Quoi faire en ville",
      id: "terme-2015-12-06-16-23-38-86966221081"
	},
	{
      terme: "Revue de presse",
      id: "terme-2015-12-06-16-23-38-86966221107"
	},
	{
      terme: "Société",
      id: "terme-2015-12-06-16-23-35-86966220949"
	},
	{
      terme: "Vie culturelle",
      id: "terme-2015-12-06-16-23-44-86966221481"
	}
 ]

**Comment by alainf** [comment]
Voir aussi : /info/accueil-sections-et-sujets.json

**Comment by millette** [comment]
Ack, je vais intégrer <https://github.com/alclro/mmmm/blob/master/info/accueil-sections-et-sujets.json>.

**Comment by millette** [comment]
J'ai corrigé le JSON.

```
yarn run jsonlint
```
Toujours pratique.
