### ISSUE TITLE
Accueil

### ISSUE THREAD

**Issue by alainf** [alclro/mmmm#9]
- [x] Identifier les json à utiliser
- [x] Afficher les brèves
- [x] Afficher tous les articles
- [x] Afficher tous les articles, en ordre de pertinence
- [x] Afficher pagination convenablement
- [x] Pagination en bas d'écran
- [x] Pagination dans le breadcrumb (précédent et suivant)

**Comment by millette** [comment]
Reste les brèves à terminer demain, sera pas long à faire.

Remarque la liste de checkbox du issue. Tu peux éditer le issue et voir comment c'est fait dans le markdown. Pratique pour des mini sous-taches.

**Comment by millette** [comment]
Voilà pour une première étape, même si ce n'est pas 100% parfait encore.
